# SPDX-License-Identifier: MIT
"""Acceptance check 12: build never overwrites work it did not write."""
import os

from conftest import FIXTURE_PACK, FRONT
from slopmill import cli

ISSUE = FRONT + """{#a}
A paragraph with **a coloured phrase**{.green} and [a link](https://example.com).

{#b}
## A heading

::: {.figure #c}
![A picture](pic.jpg)

Its caption.
:::

::: {.concept label="A Term" #d}
What the term means.
:::

::: {.closing #e}
Goodbye for now.
:::
"""


def _setup(tmp_path):
    (tmp_path / "issue.md").write_text(ISSUE, encoding="utf-8")
    return str(tmp_path / "issue.md")


def build(path, *extra):
    return cli.main(["build", path, "--pack", FIXTURE_PACK, "--no-asset-check", *extra])


def test_12_fresh_build_then_rebuild(tmp_path, capsys):
    p = _setup(tmp_path)
    assert build(p) == 0
    for name in cli.OUTPUTS:
        assert (tmp_path / name).exists()
    assert (tmp_path / cli.STATE).exists()
    assert build(p) == 0
    assert "unchanged" in capsys.readouterr().out


def test_12_refuses_hand_written_body(tmp_path, capsys):
    p = _setup(tmp_path)
    (tmp_path / "body.html").write_text("<p>hand written</p>\n")
    assert build(p) == 1
    err = capsys.readouterr().err
    assert "was not written by slopmill" in err and "nothing was written" in err
    assert (tmp_path / "body.html").read_text() == "<p>hand written</p>\n"
    assert not (tmp_path / "meta.json").exists()   # nothing at all was written
    assert build(p, "--force") == 0
    assert "Generated by slopmill" in (tmp_path / "body.html").read_text()


def test_12_refuses_hand_edited_output(tmp_path, capsys):
    p = _setup(tmp_path)
    assert build(p) == 0
    meta = tmp_path / "meta.json"
    meta.write_text(meta.read_text().replace('"number": 99', '"number": 23'))
    # change the source so the build has something new to write
    src = tmp_path / "issue.md"
    src.write_text(src.read_text().replace("## A heading", "## Two Steps Onward"))
    assert build(p) == 1
    assert "meta.json was edited after slopmill wrote it" in capsys.readouterr().err
    assert '"number": 23' in meta.read_text()
    assert "A heading" in (tmp_path / "body.html").read_text()


def test_12_source_change_rebuilds_own_output(tmp_path):
    p = _setup(tmp_path)
    assert build(p) == 0
    src = tmp_path / "issue.md"
    src.write_text(src.read_text().replace("## A heading", "## Two Steps Onward"))
    assert build(p) == 0
    assert "Two Steps Onward" in (tmp_path / "body.html").read_text()


def test_compile_error_exit_code(tmp_path, capsys):
    p = tmp_path / "issue.md"
    p.write_text("---\nnumber: 1\n---\n\nNo id.\n")
    assert build(str(p)) == 1
    assert "problems" in capsys.readouterr().err
